'use client'

import { useMemo, useRef, useState } from 'react'
import Link from 'next/link'
import { MonoLabel, SpecPill, StampButton } from '@/components/folio/primitives'
import { CardRenderer } from '@/components/cards/card-renderer'
import { cardsApi } from '@/lib/cards/api'
import { canShareFiles, downloadCard, shareCard } from '@/lib/cards/export'
import type { Card, CardBundle } from '@/lib/cards/types'
import { cn } from '@/lib/utils'
