'use client'

import { useMemo, useRef, useState } from 'react'
import { MonoLabel, StampButton } from '@/components/folio/primitives'
import { CardRenderer } from '@/components/cards/card-renderer'
import { ProfileShowcase } from '@/components/profile/showcase'
import { canShareFiles, downloadCard, shareCard } from '@/lib/cards/export'
import type { ProfileAlbum, ProfilePhoto } from '@/lib/profile/api'
import type { Card, CardBundle } from '@/lib/cards/types'
import { cn } from '@/lib/utils'
