'use client'

import { useState, useCallback } from 'react'
import { useRouter, useParams, useSearchParams } from 'next/navigation'
import Link from 'next/link'
import { createClient } from '@/lib/supabase/client'
import { MAGAZINE_TEMPLATES } from '@/lib/magazine-templates'
import { Upload, Image as ImageIcon, Calendar, ArrowRight, Loader2 } from 'lucide-react'

export default function UseTemplatePage() {
  const router = useRouter()
  const params = useParams()
  const searchParams = useSearchParams()
  const id = params.id as string
  const eventIdFromUrl = searchParams.get('eventId')
  
  const template = MAGAZINE_TEMPLATES.find(t => t.id === id)
  const [loading, setLoading] = useState(false)
  const [uploading, setUploading] = useState(false)
  const [hostedEvents, setHostedEvents] = useState<any[]>([])
  const [view, setView] = useState<'selection' | 'upload' | 'event'>('selection')

  // Fetch events when needed
  const loadEvents = useCallback(async () => {
    const supabase = createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return

    const { data } = await supabase
      .from('events')
      .select('id, title, event_date')
      .eq('host_id', user.id)
      .order('created_at', { ascending: false })
    
    setHostedEvents(data || [])
  }, [])

  if (!template) return null

  const handleEventSelect = async (selectedEventId: string) => {
    setLoading(true)
    const supabase = createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return

    // Fetch some photos from the event to auto-layout
    const { data: photos } = await supabase
      .from('photos')
      .select('id, thumbnail_url, blob_url')
      .eq('event_id', selectedEventId)
      .limit(10)

    const photoUrls = (photos || []).map(p => p.thumbnail_url || p.blob_url).filter(Boolean)

    // Create album
    const { data: album } = await supabase
      .from('albums')
      .insert({
        event_id: selectedEventId,
        owner_id: user.id,
        title: `${template.name} - Volume I`,
        layout_data: { 
          templateId: template.id,
          autoGenerated: true,
          initialPhotos: photoUrls
        }
      })
      .select()
      .single()

    if (album) {
      router.push(`/dashboard/templates/builder/${album.id}`)
    }
  }

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files
    if (!files || files.length === 0) return

    setUploading(true)
    const supabase = createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return

    // 1. Create a "Shadow Event" for these photos (Ad-hoc collection)
    const { data: event } = await supabase
      .from('events')
      .insert({
        host_id: user.id,
        title: `Upload: ${new Date().toLocaleDateString()}`,
        status: 'draft'
      })
      .select()
      .single()

    if (!event) {
        setUploading(false)
        return
    }

    // 2. Upload photos
    const uploadedUrls: string[] = []
    for (let i = 0; i < Math.min(files.length, 10); i++) {
      const file = files[i]
      const path = `${user.id}/${event.id}/${Math.random().toString(36).slice(2)}.jpg`
      const { data, error } = await supabase.storage.from('photos').upload(path, file)
      
      if (data) {
        const { data: { publicUrl } } = supabase.storage.from('photos').getPublicUrl(path)
        uploadedUrls.push(publicUrl)
        
        // Register in DB
        await supabase.from('photos').insert({
          event_id: event.id,
          uploader_id: user.id,
          blob_url: publicUrl,
          status: 'approved'
        })
      }
    }

    // 3. Create album and redirect to builder
    const { data: album } = await supabase
      .from('albums')
      .insert({
        event_id: event.id,
        owner_id: user.id,
        title: `${template.name} Volume`,
        layout_data: { 
          templateId: template.id,
          autoGenerated: true,
          initialPhotos: uploadedUrls
        }
      })
      .select()
      .single()

    if (album) {
      router.push(`/dashboard/templates/builder/${album.id}`)
    }
  }

  return (
    <div className="max-w-4xl mx-auto px-6 py-20 pb-32">
      <div className="text-center mb-16">
        <span className="text-[10px] uppercase tracking-[0.3em] font-bold text-primary mb-4 block underline underline-offset-8">Step 02</span>
        <h1 className="font-serif text-5xl text-foreground mb-4 italic">Source Your Story</h1>
        <p className="text-muted-foreground font-light text-lg">
          Choose an existing event or upload fresh moments to populate {template.name}.
        </p>
      </div>

      {view === 'selection' && (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          {/* Option A: Events */}
          <button 
            onClick={() => { setView('event'); loadEvents(); }}
            className="group p-12 bg-card border border-border hover:border-primary/40 transition-all text-left flex flex-col items-center justify-center text-center gap-6 shadow-sm hover:shadow-xl hover:shadow-primary/5"
          >
            <div className="w-16 h-16 rounded-full bg-primary/5 flex items-center justify-center group-hover:scale-110 transition-transform duration-500">
              <Calendar className="w-8 h-8 text-primary font-thin" />
            </div>
            <div>
              <h3 className="font-serif text-2xl text-foreground mb-2">Connect an Event</h3>
              <p className="text-sm text-muted-foreground font-light">Use photos already uploaded by you and your guests.</p>
            </div>
            <ArrowRight className="w-5 h-5 text-muted-foreground group-hover:text-primary group-hover:translate-x-2 transition-all" />
          </button>

          {/* Option B: Direct Upload */}
          <button 
             onClick={() => setView('upload')}
             className="group p-12 bg-ink border border-ink text-white hover:bg-ink/90 transition-all text-left flex flex-col items-center justify-center text-center gap-6 shadow-xl shadow-ink/10"
          >
            <div className="w-16 h-16 rounded-full bg-white/10 flex items-center justify-center group-hover:scale-110 transition-transform duration-500">
              <Upload className="w-8 h-8 text-white font-thin" />
            </div>
            <div>
              <h3 className="font-serif text-2xl mb-2">Instant Upload</h3>
              <p className="text-sm text-white/60 font-light">Upload new photos directly to start building right now.</p>
            </div>
            <ArrowRight className="w-5 h-5 text-white/40 group-hover:text-white group-hover:translate-x-2 transition-all" />
          </button>
        </div>
      )}

      {view === 'event' && (
        <div className="bg-card border border-border p-8 animate-in fade-in slide-in-from-bottom-4">
          <div className="flex justify-between items-center mb-8 pb-4 border-b border-border">
            <h2 className="font-serif text-2xl">Select Event</h2>
            <button onClick={() => setView('selection')} className="text-[10px] uppercase tracking-widest text-muted-foreground hover:text-foreground">Cancel</button>
          </div>
          
          <div className="space-y-3">
            {hostedEvents.length > 0 ? (
              hostedEvents.map(event => (
                <button
                  key={event.id}
                  onClick={() => handleEventSelect(event.id)}
                  disabled={loading}
                  className="w-full flex items-center justify-between p-6 bg-background border border-border hover:border-primary/40 transition-colors group"
                >
                  <div className="text-left">
                    <p className="font-serif text-xl group-hover:text-primary transition-colors">{event.title}</p>
                    <p className="text-xs text-muted-foreground">{event.event_date ? new Date(event.event_date).toLocaleDateString() : 'N/A'}</p>
                  </div>
                  <ArrowRight className="w-4 h-4 text-muted-foreground opacity-0 group-hover:opacity-100 transition-all translate-x-[-10px] group-hover:translate-x-0" />
                </button>
              ))
            ) : (
              <div className="text-center py-12">
                <p className="text-muted-foreground mb-4 font-light italic">No events found.</p>
                <Link href="/dashboard/events/new" className="text-xs font-bold uppercase tracking-widest text-primary hover:underline">Create an event first</Link>
              </div>
            )}
          </div>
        </div>
      )}

      {view === 'upload' && (
        <div className="bg-card border border-border p-12 text-center animate-in fade-in slide-in-from-bottom-4">
          <div className="w-20 h-20 rounded-full bg-muted flex items-center justify-center mx-auto mb-8">
            <ImageIcon className="w-10 h-10 text-muted-foreground" />
          </div>
          <h2 className="font-serif text-3xl mb-4 italic">Choose your moments</h2>
          <p className="text-muted-foreground font-light mb-10 max-w-sm mx-auto leading-relaxed">
            Select up to 10 photos. We'll automatically place them into the {template.name} spreads for you.
          </p>

          <div className="relative">
             <input
                type="file"
                multiple
                accept="image/*"
                onChange={handleFileUpload}
                disabled={uploading}
                className="absolute inset-0 w-full h-full opacity-0 cursor-pointer z-10"
              />
              <div className="bg-ink text-white px-10 py-5 text-xs font-bold uppercase tracking-[0.3em] shadow-2xl shadow-ink/20 inline-flex items-center gap-4">
                {uploading ? (
                  <>
                    <Loader2 className="w-4 h-4 animate-spin" />
                    Processing Gallery...
                  </>
                ) : (
                  <>
                    <Upload className="w-4 h-4" />
                    Pick Photos
                  </>
                )}
              </div>
          </div>
          
          <button 
            onClick={() => setView('selection')} 
            disabled={uploading}
            className="block mx-auto mt-8 text-[10px] uppercase tracking-widest text-muted-foreground hover:text-foreground disabled:opacity-0 transition-all"
          >
            ← Change selection method
          </button>
        </div>
      )}

      {loading && (
        <div className="fixed inset-0 bg-background/80 backdrop-blur-sm z-[100] flex flex-col items-center justify-center">
            <div className="w-16 h-16 border-t-2 border-primary rounded-full animate-spin mb-6" />
            <p className="font-serif text-2xl animate-pulse">Designing your publication...</p>
        </div>
      )}
    </div>
  )
}
