'use client'

import { useState, useCallback, useEffect, useRef } from 'react'
import { useRouter, useParams, useSearchParams } from 'next/navigation'
import Link from 'next/link'
import { createClient } from '@/lib/supabase/client'
import { ALL_MAGAZINE_TEMPLATES } from '@/lib/magazine-templates'
import { Upload, Image as ImageIcon, Calendar, ArrowRight, Loader2 } from 'lucide-react'

export default function UseTemplatePage() {
  const router = useRouter()
  const params = useParams()
  const searchParams = useSearchParams()
  const id = params.id as string
  const eventIdFromUrl = searchParams.get('eventId')
  
  const template = ALL_MAGAZINE_TEMPLATES.find(t => t.id === id)
  const [loading, setLoading] = useState(false)
  const [uploading, setUploading] = useState(false)
  const [hostedEvents, setHostedEvents] = useState<any[]>([])
  const [view, setView] = useState<'selection' | 'upload' | 'event'>('selection')
  const autoCreateTriggeredRef = useRef(false)

  // Fetch events when needed
  const loadEvents = useCallback(async () => {
    const supabase = createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return

    const { data } = await supabase
      .from('events')
      .select('id, title, event_date')
      .eq('host_id', user.id)
      .order('created_at', { ascending: false })
    
    setHostedEvents(data || [])
  }, [])

  if (!template) return null
  const templateSpreads = template.spreads.length > 0 ? template.spreads : [
    {
      id: `${template.id}-cover`,
      isCover: true,
      background: '#f8f4ec',
      elements: [],
      front: { background: '#f8f4ec', elements: [] },
      back: { background: '#ffffff', elements: [] },
    },
    {
      id: `${template.id}-spread-1`,
      isCover: false,
      background: '#ffffff',
      elements: [],
      front: { background: '#ffffff', elements: [] },
      back: { background: '#ffffff', elements: [] },
    },
  ]

  const handleEventSelect = async (selectedEventId: string) => {
    setLoading(true)
    const supabase = createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) {
      setLoading(false)
      return
    }

    // Fetch some photos from the event to auto-layout
    const { data: photos } = await supabase
      .from('photos')
      .select('id, thumbnail_url, blob_url')
      .eq('event_id', selectedEventId)
      .limit(20)

    const photoUrls = (photos || []).map(p => p.blob_url || p.thumbnail_url).filter(Boolean)

    // Create album
    const { data: album } = await supabase
      .from('albums')
      .insert({
        event_id: selectedEventId,
        owner_id: user.id,
        title: `${template.name} - Volume I`,
        layout_data: { 
          productType: 'magazine',
          templateId: template.id,
          autoGenerated: true,
          initialPhotos: photoUrls,
          spreads: templateSpreads,
        }
      })
      .select()
      .single()

    if (album) {
      router.push(`/dashboard/templates/editor/${album.id}`)
      return
    }

    setLoading(false)
  }

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files
    if (!files || files.length === 0) return

    setUploading(true)
    const supabase = createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) {
      setUploading(false)
      return
    }

    // 1. Create a "Shadow Event" for these photos (Ad-hoc collection)
    const { data: event } = await supabase
      .from('events')
      .insert({
        host_id: user.id,
        title: `Upload: ${new Date().toLocaleDateString()}`,
        status: 'draft'
      })
      .select()
      .single()

    if (!event) {
        setUploading(false)
        return
    }

    // 2. Upload photos
    const uploadedUrls: string[] = []
    for (let i = 0; i < Math.min(files.length, 20); i++) {
      const file = files[i]
      const path = `${user.id}/${event.id}/${Math.random().toString(36).slice(2)}.jpg`
      const { data } = await supabase.storage.from('photos').upload(path, file)
      
      if (data) {
        const { data: { publicUrl } } = supabase.storage.from('photos').getPublicUrl(path)
        uploadedUrls.push(publicUrl)
        
        // Register in DB
        await supabase.from('photos').insert({
          event_id: event.id,
          uploader_id: user.id,
          blob_url: publicUrl,
          status: 'approved'
        })
      }
    }

    // 3. Create album and redirect to builder
    const { data: album } = await supabase
      .from('albums')
      .insert({
        event_id: event.id,
        owner_id: user.id,
        title: `${template.name} Volume`,
        layout_data: { 
          productType: 'magazine',
          templateId: template.id,
          autoGenerated: true,
          initialPhotos: uploadedUrls,
          spreads: templateSpreads,
        }
      })
      .select()
      .single()

    if (album) {
      router.push(`/dashboard/templates/editor/${album.id}`)
      return
    }

    setUploading(false)
  }

  const selectEventSource = () => {
    setView('event')
    loadEvents()
  }

  useEffect(() => {
    if (eventIdFromUrl) {
      void loadEvents().then(() => setView('event'))
    }
  }, [eventIdFromUrl, loadEvents])

  useEffect(() => {
    if (!eventIdFromUrl || autoCreateTriggeredRef.current) return
    autoCreateTriggeredRef.current = true
    void handleEventSelect(eventIdFromUrl)
  }, [eventIdFromUrl])

  return (
    <div className="max-w-4xl mx-auto px-6 py-20 pb-32">
      <div className="text-center mb-20">
        <div className="flex items-center justify-center gap-4 mb-8">
          <div className="h-[1px] w-8 bg-primary/30" />
          <span className="text-[10px] uppercase tracking-[0.4em] font-bold text-primary">Curation Step 02</span>
          <div className="h-[1px] w-8 bg-primary/30" />
        </div>
        <h1 className="font-serif text-5xl md:text-6xl text-ink mb-6 tracking-tight">Source Your <span className="italic text-terracotta">Story</span></h1>
        <p className="text-pencil font-serif italic text-xl max-w-xl mx-auto leading-relaxed">
          Select a curated gallery from your events or upload fresh moments to begin your editorial journey with <span className="text-ink font-semibold not-italic">{template.name}</span>.
        </p>
      </div>

      {view === 'selection' && (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 lg:gap-12">
          {/* Option A: Events */}
          <button 
            onClick={selectEventSource}
            className="group relative p-12 transition-all duration-700 text-center flex flex-col items-center justify-center gap-8 shadow-sm hover:shadow-2xl hover:shadow-primary/5 rounded-lg overflow-hidden border border-[#DDD8CE]"
            style={{ backgroundColor: '#F5F0E8', color: '#1C1814' }}
          >
            <div className="absolute inset-0 bg-gradient-to-br from-primary/5 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-700" />
            <div className="relative z-10">
              <div className="w-20 h-20 rounded-full bg-primary/5 flex items-center justify-center mb-6 group-hover:scale-110 transition-transform duration-700 border border-primary/10">
                <Calendar className="w-10 h-10 text-primary font-thin" strokeWidth={1} />
              </div>
              <h3 className="font-serif text-3xl mb-4 tracking-tight" style={{ color: '#1C1814' }}>Connect an Event</h3>
              <p className="text-sm font-light leading-relaxed max-w-[240px] mx-auto opacity-70" style={{ color: '#1C1814' }}>
                Access curated galleries from your hosted events and weddings.
              </p>
            </div>
            <div className="relative z-10 mt-4 flex items-center gap-3 text-[10px] font-bold uppercase tracking-[0.3em] text-primary opacity-60 group-hover:opacity-100 transition-all">
              Select Gallery <ArrowRight className="w-4 h-4 group-hover:translate-x-2 transition-transform" />
            </div>
          </button>

          {/* Option B: Direct Upload */}
          <button 
             onClick={() => setView('upload')}
             className="group relative p-12 transition-all duration-700 text-center flex flex-col items-center justify-center gap-8 shadow-2xl shadow-ink/20 rounded-lg overflow-hidden border border-[#1C1814]"
             style={{ backgroundColor: '#1C1814', color: '#F5F0E8' }}
          >
            <div className="absolute inset-0 bg-gradient-to-tr from-white/5 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-700" />
            <div className="absolute inset-0 film-grain opacity-10 pointer-events-none" />
            
            <div className="relative z-10">
              <div className="w-20 h-20 rounded-full bg-white/5 flex items-center justify-center mb-6 group-hover:scale-110 transition-transform duration-700 border border-white/10">
                <Upload className="w-10 h-10 font-thin" style={{ color: '#F5F0E8' }} strokeWidth={1} />
              </div>
              <h3 className="font-serif text-3xl mb-4 tracking-tight" style={{ color: '#F5F0E8' }}>Instant Upload</h3>
              <p className="text-sm font-light leading-relaxed max-w-[240px] mx-auto opacity-60" style={{ color: '#F5F0E8' }}>
                Start from scratch with high-resolution photos from your device.
              </p>
            </div>
            
            <div className="relative z-10 mt-4 flex items-center gap-3 text-[10px] font-bold uppercase tracking-[0.3em] opacity-60 group-hover:opacity-100 transition-all" style={{ color: '#F5F0E8' }}>
              Upload Now <ArrowRight className="w-4 h-4 group-hover:translate-x-2 transition-transform" />
            </div>
          </button>
        </div>
      )}

      {view === 'event' && (
        <div className="bg-card border border-border p-8 animate-in fade-in slide-in-from-bottom-4">
          <div className="flex justify-between items-center mb-8 pb-4 border-b border-border">
            <h2 className="font-serif text-2xl">Select Event</h2>
            <button onClick={() => setView('selection')} className="text-[10px] uppercase tracking-widest text-muted-foreground hover:text-foreground">Cancel</button>
          </div>
          
          <div className="space-y-3">
            {hostedEvents.length > 0 ? (
              hostedEvents.map(event => (
                <button
                  key={event.id}
                  onClick={() => handleEventSelect(event.id)}
                  disabled={loading}
                  className="w-full flex items-center justify-between p-6 bg-background border border-border hover:border-primary/40 transition-colors group"
                >
                  <div className="text-left">
                    <p className="font-serif text-xl group-hover:text-primary transition-colors">{event.title}</p>
                    <p className="text-xs text-muted-foreground">{event.event_date ? new Date(event.event_date).toLocaleDateString() : 'N/A'}</p>
                  </div>
                  <ArrowRight className="w-4 h-4 text-muted-foreground opacity-0 group-hover:opacity-100 transition-all translate-x-[-10px] group-hover:translate-x-0" />
                </button>
              ))
            ) : (
              <div className="text-center py-12">
                <p className="text-muted-foreground mb-4 font-light italic">No events found.</p>
                <Link href="/dashboard/events/new" className="text-xs font-bold uppercase tracking-widest text-primary hover:underline">Create an event first</Link>
              </div>
            )}
          </div>
        </div>
      )}

      {view === 'upload' && (
        <div className="bg-card border border-border p-12 text-center animate-in fade-in slide-in-from-bottom-4">
          <div className="w-20 h-20 rounded-full bg-muted flex items-center justify-center mx-auto mb-8">
            <ImageIcon className="w-10 h-10 text-muted-foreground" />
          </div>
          <h2 className="font-serif text-3xl mb-4 italic">Choose your moments</h2>
          <p className="text-muted-foreground font-light mb-10 max-w-sm mx-auto leading-relaxed">
            Select up to 10 photos. We'll automatically place them into the {template.name} spreads for you.
          </p>

          <div className="relative">
             <input
                type="file"
                multiple
                accept="image/*"
                onChange={handleFileUpload}
                disabled={uploading}
                className="absolute inset-0 w-full h-full opacity-0 cursor-pointer z-10"
              />
              <div className="bg-ink text-white px-10 py-5 text-xs font-bold uppercase tracking-[0.3em] shadow-2xl shadow-ink/20 inline-flex items-center gap-4">
                {uploading ? (
                  <>
                    <Loader2 className="w-4 h-4 animate-spin" />
                    Processing Gallery...
                  </>
                ) : (
                  <>
                    <Upload className="w-4 h-4" />
                    Pick Photos
                  </>
                )}
              </div>
          </div>
          
          <button 
            onClick={() => setView('selection')} 
            disabled={uploading}
            className="block mx-auto mt-8 text-[10px] uppercase tracking-widest text-muted-foreground hover:text-foreground disabled:opacity-0 transition-all"
          >
            ← Change selection method
          </button>
        </div>
      )}

      {loading && (
        <div className="fixed inset-0 bg-background/80 backdrop-blur-sm z-[100] flex flex-col items-center justify-center">
            <div className="w-16 h-16 border-t-2 border-primary rounded-full animate-spin mb-6" />
            <p className="font-serif text-2xl animate-pulse">Designing your publication...</p>
        </div>
      )}
    </div>
  )
}
