'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { createClient } from '@/lib/supabase/client'
import { apiClient } from '@/lib/api-client'
import { ALL_MAGAZINE_TEMPLATES } from '@/lib/magazine-templates'
import { Calendar, MapPin, ArrowRight, ChevronLeft, Sparkles, BookOpen, Layers } from 'lucide-react'

export default function NewEventPage() {
  const router = useRouter()
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  
  // Step State: 'options' | 'template-select' | 'details'
  const [step, setStep] = useState<'options' | 'template-select' | 'details'>('options')
  const [selectedTemplateId, setSelectedTemplateId] = useState<string | null>(null)

  const selectedTemplate = ALL_MAGAZINE_TEMPLATES.find(t => t.id === selectedTemplateId)

  async function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault()
    setLoading(true)
    setError(null)

    const formData = new FormData(e.currentTarget)
    const title = formData.get('title') as string
    const description = formData.get('description') as string
    const event_date = formData.get('date') as string
    const location = formData.get('location') as string

    const supabase = createClient()
    const { data: { user } } = await supabase.auth.getUser()

    if (!user) {
      setError('You must be logged in to create an event')
      setLoading(false)
      return
    }

    try {
      // 1. Create the event
      const eventData = await apiClient.post('/api/events', {
        title,
        description: description || null,
        eventDate: event_date || null,
        settings: {
          location: location || null,
          templateId: selectedTemplateId || null,
          allow_guest_uploads: false, // default guest uploads to false under new role system
          auto_approve_guest_uploads: false
        },
      })

      // 2. If Option 2 (template selected), create the album automatically
      if (selectedTemplateId && selectedTemplate) {
        const spreads = selectedTemplate.spreads.length > 0 ? selectedTemplate.spreads : [
          {
            id: `${selectedTemplate.id}-cover`,
            isCover: true,
            background: '#f8f4ec',
            elements: [],
            front: { background: '#f8f4ec', elements: [] },
            back: { background: '#ffffff', elements: [] },
          },
          {
            id: `${selectedTemplate.id}-spread-1`,
            isCover: false,
            background: '#ffffff',
            elements: [],
            front: { background: '#ffffff', elements: [] },
            back: { background: '#ffffff', elements: [] },
          }
        ]

        await apiClient.post('/api/albums', {
          eventId: eventData.id,
          title: `${selectedTemplate.name} - Volume I`,
          templateId: selectedTemplateId,
          layoutData: {
            productType: 'magazine',
            templateId: selectedTemplateId,
            autoGenerated: false,
            spreads
          }
        })
      } else {
        // Option 1: Create a default Blank Canvas album
        await apiClient.post('/api/albums', {
          eventId: eventData.id,
          title: `Blank Volume`,
          layoutData: {
            productType: 'magazine',
            autoGenerated: false,
            spreads: [
              {
                id: `blank-cover`,
                isCover: true,
                background: '#f8f4ec',
                elements: [],
                front: { background: '#f8f4ec', elements: [] },
                back: { background: '#ffffff', elements: [] },
              }
            ]
          }
        })
      }

      router.push(`/dashboard/events/${eventData.id}`)
    } catch (insertError: any) {
      setError(insertError.message || 'Failed to initialize event creation')
      setLoading(false)
    }
  }

  return (
    <div className="max-w-4xl mx-auto px-6 py-20 pb-32">
      
      {/* ── BREADCRUMB / BACK ACTIONS ─────────────────────────────────── */}
      <div className="mb-12">
        {step === 'options' && (
          <Link href="/dashboard/events" className="text-[10px] uppercase tracking-[0.3em] font-bold text-muted-foreground hover:text-foreground transition-all">
            ← Back to Events
          </Link>
        )}
        {step === 'template-select' && (
          <button 
            onClick={() => setStep('options')} 
            className="text-[10px] uppercase tracking-[0.3em] font-bold text-muted-foreground hover:text-foreground transition-all cursor-pointer"
          >
            ← Back to Options
          </button>
        )}
        {step === 'details' && (
          <button 
            onClick={() => setStep(selectedTemplateId ? 'template-select' : 'options')} 
            className="text-[10px] uppercase tracking-[0.3em] font-bold text-muted-foreground hover:text-foreground transition-all cursor-pointer"
          >
            ← Back
          </button>
        )}
      </div>

      {/* ── STEP 1: OPTIONS SELECTION ─────────────────────────────────── */}
      {step === 'options' && (
        <div className="space-y-16">
          <div className="text-center max-w-2xl mx-auto">
            <h1 className="font-serif text-5xl md:text-6xl text-foreground mb-6">Create New Collection</h1>
            <p className="text-muted-foreground text-lg font-light leading-relaxed">
              Choose your creative starting point. Build everything manually from scratch or utilize an artist-crafted album template.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {/* Option A: Create From Scratch */}
            <div 
              onClick={() => {
                setSelectedTemplateId(null)
                setStep('details')
              }}
              className="group p-10 bg-card border border-border hover:border-primary/40 cursor-pointer transition-all flex flex-col justify-between text-left"
            >
              <div>
                <div className="w-12 h-12 bg-primary/5 border border-primary/10 rounded-full flex items-center justify-center mb-6">
                  <Layers className="w-6 h-6 text-primary" strokeWidth={1.5} />
                </div>
                <h3 className="font-serif text-2xl text-foreground mb-3">Option 1 — Create From Scratch</h3>
                <p className="text-sm text-muted-foreground font-light leading-relaxed mb-8">
                  Start with a blank slate. You will have full manual control over uploading photos, adding text layout components, and grouping albums exactly how you visualize them.
                </p>
              </div>
              <span className="text-[10px] uppercase tracking-[0.2em] font-bold text-primary flex items-center gap-1 opacity-60 group-hover:opacity-100 group-hover:translate-x-1 transition-all">
                Start Scratch Build <ArrowRight className="w-3.5 h-3.5" />
              </span>
            </div>

            {/* Option B: Use Popular Album Layout */}
            <div 
              onClick={() => {
                setStep('template-select')
              }}
              className="group p-10 bg-card border border-border hover:border-primary/40 cursor-pointer transition-all flex flex-col justify-between text-left"
            >
              <div>
                <div className="w-12 h-12 bg-secondary/10 border border-secondary/20 rounded-full flex items-center justify-center mb-6">
                  <Sparkles className="w-6 h-6 text-secondary" strokeWidth={1.5} />
                </div>
                <h3 className="font-serif text-2xl text-foreground mb-3">Option 2 — Use Popular Layout</h3>
                <p className="text-sm text-muted-foreground font-light leading-relaxed mb-8">
                  Begin with a stunning, pre-designed editorial structure. Choose from our popular catalog styles (Wedding, Voyage, Fashion Portfolio) to structure your album spreads instantly.
                </p>
              </div>
              <span className="text-[10px] uppercase tracking-[0.2em] font-bold text-secondary flex items-center gap-1 opacity-60 group-hover:opacity-100 group-hover:translate-x-1 transition-all">
                Select Editorial Design <ArrowRight className="w-3.5 h-3.5" />
              </span>
            </div>
          </div>
        </div>
      )}

      {/* ── STEP 2: SELECT POPULAR TEMPLATE ──────────────────────────── */}
      {step === 'template-select' && (
        <div className="space-y-12">
          <div className="text-center max-w-2xl mx-auto">
            <span className="text-[10px] uppercase tracking-[0.25em] text-secondary font-bold mb-3 block">Step 2 of 3</span>
            <h2 className="font-serif text-4xl text-foreground mb-4">Select Album Style</h2>
            <p className="text-muted-foreground font-light text-sm">
              Choose an editorial voice that encapsulates the theme of your photos.
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
            {ALL_MAGAZINE_TEMPLATES.map(template => (
              <div
                key={template.id}
                onClick={() => {
                  setSelectedTemplateId(template.id)
                  setStep('details')
                }}
                className="group border border-border bg-card rounded-md overflow-hidden cursor-pointer hover:border-secondary/40 hover:shadow-md transition-all flex flex-col"
              >
                <div className="aspect-[3/4] overflow-hidden relative bg-muted">
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img
                    src={template.thumbnail}
                    alt={template.name}
                    className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                  />
                  <div className="absolute top-2 left-2 px-2 py-1 bg-background/80 text-[8px] font-bold uppercase tracking-wider">
                    {template.category}
                  </div>
                </div>
                <div className="p-4 flex-1 flex flex-col justify-between">
                  <div>
                    <h4 className="font-serif text-lg text-foreground mb-1 leading-tight">{template.name}</h4>
                    <p className="text-xs text-muted-foreground line-clamp-2 font-light">{template.description}</p>
                  </div>
                  <div className="mt-4 pt-3 border-t border-border flex justify-between items-center text-[9px] uppercase tracking-widest text-secondary font-bold">
                    <span>Select Template</span>
                    <ArrowRight className="w-3 h-3 group-hover:translate-x-1 transition-transform" />
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* ── STEP 3: DETAILS FORM ─────────────────────────────────────── */}
      {step === 'details' && (
        <div className="max-w-2xl mx-auto space-y-12 animate-in fade-in slide-in-from-bottom-4 duration-200">
          <div className="mb-12">
            <span className="text-[10px] uppercase tracking-[0.25em] text-primary font-bold mb-3 block">
              {selectedTemplateId ? 'Step 3 of 3' : 'Step 2 of 2'}
            </span>
            <h1 className="font-serif text-5xl text-foreground mb-4">Collection Details</h1>
            <p className="text-muted-foreground text-sm font-light leading-relaxed">
              {selectedTemplateId ? (
                <>Creating event structure using popular album template: <strong className="text-foreground">{selectedTemplate?.name}</strong></>
              ) : (
                <>Initializing a blank event portfolio with manual album canvas</>
              )}
            </p>
          </div>

          {error && (
            <div className="p-4 bg-red-500/10 border border-red-500/20 text-red-400 text-sm">
              {error}
            </div>
          )}

          <form onSubmit={handleSubmit} className="space-y-12 bg-card p-10 border border-border">
            <div className="space-y-6">
              <div>
                <label htmlFor="title" className="block text-[10px] uppercase tracking-[0.2em] font-bold text-muted-foreground mb-3">
                  Event Title *
                </label>
                <input
                  id="title"
                  name="title"
                  type="text"
                  required
                  className="w-full px-0 py-3 bg-transparent border-b border-border text-2xl font-serif text-foreground placeholder:text-muted-foreground/30 focus:outline-none focus:border-primary transition-colors"
                  placeholder="E.g. Summer in Tuscany"
                />
              </div>

              <div>
                <label htmlFor="description" className="block text-[10px] uppercase tracking-[0.2em] font-bold text-muted-foreground mb-3">
                  Description
                </label>
                <textarea
                  id="description"
                  name="description"
                  rows={2}
                  className="w-full px-0 py-3 bg-transparent border-b border-border text-foreground placeholder:text-muted-foreground/30 focus:outline-none focus:border-primary transition-colors resize-none font-light"
                  placeholder="Capturing the golden hours..."
                />
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-12">
                <div>
                  <label htmlFor="date" className="block text-[10px] uppercase tracking-[0.2em] font-bold text-muted-foreground mb-3">
                    Date
                  </label>
                  <input
                    id="date"
                    name="date"
                    type="date"
                    className="w-full px-0 py-3 bg-transparent border-b border-border text-foreground focus:outline-none focus:border-primary transition-colors text-sm"
                  />
                </div>

                <div>
                  <label htmlFor="location" className="block text-[10px] uppercase tracking-[0.2em] font-bold text-muted-foreground mb-3">
                    Location
                  </label>
                  <input
                    id="location"
                    name="location"
                    type="text"
                    className="w-full px-0 py-3 bg-transparent border-b border-border text-foreground placeholder:text-muted-foreground/30 focus:outline-none focus:border-primary transition-colors text-sm"
                    placeholder="Italy"
                  />
                </div>
              </div>
            </div>

            <div className="pt-8">
              <button
                type="submit"
                disabled={loading}
                className="w-full bg-primary text-primary-foreground py-5 text-xs font-bold uppercase tracking-[0.3em] hover:bg-primary/90 transition-all shadow-xl shadow-primary/20 disabled:opacity-50 disabled:cursor-not-allowed cursor-pointer"
              >
                {loading ? 'Designing Album spreads...' : 'Initialize Event & Album'}
              </button>
            </div>
          </form>
        </div>
      )}
      
    </div>
  )
}
